# Generated by Django 4.2.2 on 2023-06-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefactor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCompleto', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=10)),
                ('UbicacionDomicilio', models.CharField(max_length=100)),
                ('Anonimo', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Requerimiento', models.CharField(max_length=100)),
                ('Imagenes', models.TextField()),
                ('FechaInicio', models.DateTimeField()),
                ('FechaCierre', models.DateTimeField()),
                ('Estado', models.BooleanField(default=True)),
                ('InstitucionAsiloID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InstitucionAsilo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('NIT', models.CharField(max_length=20)),
                ('NombreRepresentantePrincipal', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=20)),
                ('Celular', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=200)),
                ('Localizacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecojosProgramados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CampaniaID', models.IntegerField()),
                ('FechaRecoleccion', models.DateTimeField()),
                ('Responsable', models.CharField(max_length=100)),
                ('Campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caambu.campania')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CampaniaID', models.IntegerField()),
                ('BenefactorID', models.IntegerField()),
                ('RecogidaPorAsilo', models.BooleanField(default=False)),
                ('FechaRecoleccion', models.DateTimeField()),
                ('RecibidoPorAsilo', models.BooleanField(default=False)),
                ('Benefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caambu.benefactor')),
                ('Campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caambu.campania')),
            ],
        ),
        migrations.AddField(
            model_name='campania',
            name='InstitucionAsilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caambu.institucionasilo'),
        ),
    ]
